import React from 'react';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import CommonHeroSection from '@/components/Common/Banner/CommonHerosection';
import Schedule from '@/components/sections/Schedule';
import { getSeoMetadata } from '@/services/seoService';

import { blogPosts as mockBlogPosts } from '@/data/blogData';

// Dynamic SEO metadata generation
export async function generateMetadata({ params }) {
    const { slug } = await params;
    const path = `/blogs/${slug}`;
    const seo = await getSeoMetadata(path);
    return seo;
}

// SSG paths pre-generation
export async function generateStaticParams() {
    try {
        const baseUrl = process.env.NEXT_PUBLIC_API_URL;
        if (baseUrl) {
            const res = await fetch(`${baseUrl}public/v1/blog/get-blogs`, { next: { revalidate: 60 } });
            const data = await res.json();
            if (data.success && data.data && data.data.length > 0) {
                return data.data.map((post) => ({
                    slug: post.url || 'placeholder',
                }));
            }
        } else {
            console.warn("NEXT_PUBLIC_API_URL is undefined. Using mock data for static params.");
        }
    } catch (error) {
        console.error("Failed to fetch blogs for static params:", error);
    }

    // Fallback to mock data so you can still view the old URLs in your browser
    return mockBlogPosts.map((post) => ({
        slug: post.slug,
    }));
}

async function getBlogData(slug) {
    try {
        const baseUrl = process.env.NEXT_PUBLIC_API_URL;
        if (baseUrl) {
            const res = await fetch(`${baseUrl}public/v1/blog/get-blog/${slug}`, {
                next: { revalidate: 60 }
            });
            const data = await res.json();

            if (data.success && data.data && data.data.length > 0) {
                return data.data[0];
            }
        }
    } catch (error) {
        console.error("Failed to fetch blog post:", error);
    }

    // Fallback to mock data if backend doesn't have it
    const mockPost = mockBlogPosts.find(p => p.slug === slug);
    if (mockPost) {
        // Map mock data structure to match expected backend structure for the simple design
        return {
            ...mockPost,
            url: mockPost.slug,
            description: `<p>${mockPost.description}</p>`, // Simple rich text fallback
            createdAt: mockPost.date,
        };
    }

    return null;
}

export default async function BlogDetailPage({ params }) {
    const { slug } = await params;

    // Fetch blog from backend
    const post = await getBlogData(slug);

    if (!post) {
        notFound();
    }

    // Split title for CommonHeroSection
    const words = post.title ? post.title.split(' ') : ['Blog', 'Post'];
    const highlightedTitle = words.slice(0, 3).join(' ');
    const plainTitle = words.slice(3).join(' ');

    // Format Date
    const postDate = post.createdAt ? new Date(post.createdAt).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
    }) : 'Recent';

    return (
        <main className="min-h-screen font-sans">
            {/* Scoped styles for rich text content generated by admin panel */}
            <style dangerouslySetInnerHTML={{
                __html: `
                .rich-text-content h1 { font-size: 2.25rem; font-weight: 700; color: #111; margin-top: 2rem; margin-bottom: 1rem; line-height: 1.2; font-family: inherit; }
                .rich-text-content h2 { font-size: 1.75rem; font-weight: 700; color: #111; margin-top: 2rem; margin-bottom: 1rem; line-height: 1.3; font-family: inherit; position: relative; padding-left: 1rem; }
                .rich-text-content h2::before { content: ''; position: absolute; left: 0; top: 4px; bottom: 4px; width: 4px; background-color: #A2064F; border-radius: 2px; }
                .rich-text-content h3 { font-size: 1.5rem; font-weight: 700; color: #111; margin-top: 1.5rem; margin-bottom: 0.75rem; line-height: 1.4; font-family: inherit; }
                .rich-text-content p { font-size: 1.0625rem; color: #444; line-height: 1.75; margin-bottom: 1.25rem; }
                .rich-text-content ul { list-style-type: none; padding-left: 0.5rem; margin-bottom: 1.25rem; }
                .rich-text-content ul li { font-size: 1.0625rem; color: #444; line-height: 1.6; margin-bottom: 0.75rem; position: relative; padding-left: 1.5rem; }
                .rich-text-content ul li::before { content: ''; position: absolute; left: 0; top: 0.6rem; width: 6px; height: 6px; border-radius: 50%; background-color: #A2064F; }
                .rich-text-content ol { list-style-type: decimal; padding-left: 1.5rem; margin-bottom: 1.25rem; }
                .rich-text-content ol li { font-size: 1.0625rem; color: #444; line-height: 1.6; margin-bottom: 0.75rem; }
                .rich-text-content a { color: #A2064F; text-decoration: underline; font-weight: 500; }
                .rich-text-content a:hover { color: #660033; }
                .rich-text-content blockquote { border-left: 4px solid #A2064F; margin: 1.5rem 0; color: #555; background: #FAF9F6; padding: 1.5rem; border-radius: 8px; font-style: italic; font-size: 1.125rem; }
                .rich-text-content img { max-width: 100%; height: auto; border-radius: 16px; margin: 2rem 0; box-shadow: 0 4px 20px rgba(0,0,0,0.06); }
                .rich-text-content strong { font-weight: 700; color: #222; }
            `}} />

            {/* Hero Section */}
            <CommonHeroSection
                highlightedTitle={highlightedTitle}
                plainTitle={plainTitle}
                description={post.excerpt || post.metaDescription || "Explore our latest insights and updates."}
                imageUrl={post.image || "/images/placeholder-blog.jpg"}
                imageAlt={post.title}
                breadcrumbs={[
                    { label: 'Home', href: '/' },
                    { label: 'Blogs & Articles', href: '/blogs' },
                    { label: post.title, href: `/blogs/${post.url}` }
                ]}
            />

            {/* Main Content */}
            <div className="bg-[#FAF9F6] w-full">
                <div className="max-w-[1400px] mx-auto px-[20px] md:px-[60px] lg:px-[100px] py-[60px] md:py-[100px]">
                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-[40px] lg:gap-[60px]">

                        {/* Left Column: Article Body */}
                        <article className="lg:col-span-8 bg-white rounded-[24px] p-[24px] md:p-[48px] shadow-sm border border-[#F0EFEA] overflow-hidden">
                            {/* Meta information bar */}
                            <div className="flex flex-wrap items-center gap-[16px] md:gap-[24px] pb-[24px] mb-[32px] border-b border-[#F0EFEA] text-[13px] md:text-[14px] text-[#666666] font-medium font-sans">
                                <div className="flex items-center gap-[12px]">
                                    <span className="w-[32px] h-[32px] rounded-full bg-[#A2064F]/10 text-[#A2064F] flex items-center justify-center font-bold text-[12px]">
                                        IF
                                    </span>
                                    <span className="font-semibold text-[#111111]">{post.author || 'Invest First Setup Experts'}</span>
                                </div>
                                <div className="w-[4px] h-[4px] rounded-full bg-[#CCCCCC] hidden md:block" />
                                <div className="flex items-center gap-[6px]">
                                    <svg className="w-[16px] h-[16px] text-[#A2064F]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                    </svg>
                                    <span>{postDate}</span>
                                </div>
                            </div>

                            {/* Article HTML Content */}
                            <div
                                className="rich-text-content"
                                dangerouslySetInnerHTML={{ __html: post.description || "<p>No content available for this blog post.</p>" }}
                            />
                        </article>

                        {/* Right Column: Sidebar */}
                        <aside className="lg:col-span-4 space-y-[32px]">

                            {/* Sidebar: CTA Box */}
                            <div className="bg-gradient-to-b from-[#111111] to-[#1F1F1F] rounded-[24px] p-[32px] text-white shadow-xl relative overflow-hidden">
                                <div className="absolute top-0 right-0 w-[120px] h-[120px] bg-gradient-to-bl from-[#A2064F]/30 to-transparent rounded-full blur-[40px] pointer-events-none" />
                                <div className="absolute bottom-[-40px] left-[-40px] w-[160px] h-[160px] bg-gradient-to-tr from-[#A2064F]/20 to-transparent rounded-full blur-[50px] pointer-events-none" />

                                <h3 className="text-[22px] font-bold mb-[16px] leading-[1.3] tracking-tight relative z-10 font-sans">
                                    Start Your Business in Dubai Today
                                </h3>
                                <p className="text-[13px] text-white/80 leading-[1.6] mb-[28px]">
                                    Get direct access to fast digital company registration, residency visas, and 100% foreign ownership. Let our experts guide you.
                                </p>

                                <ul className="space-y-[12px] mb-[28px] text-[13px]">
                                    <li className="flex items-center gap-[8px]">
                                        <svg className="w-4 h-4 text-[#A2064F]" fill="currentColor" viewBox="0 0 20 20">
                                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                                        </svg>
                                        Free Expert Consultation
                                    </li>
                                    <li className="flex items-center gap-[8px]">
                                        <svg className="w-4 h-4 text-[#A2064F]" fill="currentColor" viewBox="0 0 20 20">
                                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                                        </svg>
                                        100% Foreign Ownership
                                    </li>
                                    <li className="flex items-center gap-[8px]">
                                        <svg className="w-4 h-4 text-[#A2064F]" fill="currentColor" viewBox="0 0 20 20">
                                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                                        </svg>
                                        Instant Setup Process
                                    </li>
                                </ul>

                                <Link
                                    href="/contact-us"
                                    className="w-full text-center block bg-gradient-to-r from-[#A2064F] to-[#660033] hover:from-[#b90d5d] hover:to-[#7c003e] text-white px-[24px] py-[14px] rounded-full text-[14px] font-bold shadow-md hover:scale-[1.02] active:scale-95 transition-all duration-300"
                                >
                                    Contact Us Now
                                </Link>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>

            <Schedule />
        </main>
    );
}
